services:
  postgres:
    image: postgres:17-alpine
    container_name: rust-sql-orm-demo-pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5561:5432"
    volumes:
      - rust-sql-orm-demo-pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  rust-sql-orm-demo-pg-data:
    driver: local
